### ISSUE TITLE
Cert options aren't working.

### ISSUE THREAD

**Issue by pmbapat** [ist-dsi/cookbook-vault-certificate#1]
Thanks for this cookbook. Great job!

While implementing I found the custom options do not work as expected. 

Vault Command example: 
```
vault write pki_int_service/issue/service-example-com common_name="dc-srv-bdf1.service.example.com" alt_names="lb.service.example.com" ip_sans="10.10.10.10" ttl=240h
```

Equivalent of this in the recipe does not work. It just gets the cert valid for 1 hour which is very short default.

```
cert = vault_certificate 'dc-srv-bdf1.service.example.com' do
  vault_path 'pki_int_service/issue/service-example-com'
  options =  { 'alt_names' => 'lb.service.example.com', 'ip_sans' => '10.10.10.10', 'ttl' => '240h' }
end
```

Another very useful option would be to get a new cert before the current one expires. If this can be configured to say get a cert if its expiring in the next few days it would be great. 

Thanks.

**Comment by Lasering** [comment]
Try with:
```
cert = vault_certificate 'dc-srv-bdf1.service.example.com' do
  vault_path 'pki_int_service/issue/service-example-com'
  options (
    alt_names: 'lb.service.example.com',
    ip_sans: '10.10.10.10',
    ttl: '240h'
   )
end
```

> Another very useful option would be to get a new cert before the current one expires. If this can be configured to say get a cert if its expiring in the next few days it would be great.

This is already semi-implemented. The Vault pki is modeled for ephemeral certificates, so the resource cannot be constantly asking Vault for a certificate. If the certificate is still valid and its CN is the requested one, no request is made to Vault. When the certificate has expired a new certificate is requested. See [this piece of code](https://github.com/ist-dsi/cookbook-vault-certificate/blob/master/resources/vault_certificate.rb#L332) to understand it better.

If that is still not enough, make a PR.

**Comment by pmbapat** [comment]
Thanks for the reply. This is helpful. Much appreciated. 

> When the certificate has expired 

Arguably if the cert has expired, then the service using the cert will experience an outage. I'm suggesting to avoid this using some sort of threshold.

**Comment by pmbapat** [comment]
The above code did not work. Returns syntax error. I was able to get this working with below.

```
cert_hostname = 'dc-srv-bdf1.service.example.com'

node.override['vault_certificate']['options'] = {
              common_name: cert_hostname,
              alt_names: 'lb.service.example.com',
              ip_sans: '10.10.10.10',
              ttl: '240h'
}

cert = vault_certificate cert_hostname do
    vault_path 'pki_int_service/issue/service-example-com'
end
```

**Comment by Lasering** [comment]
I always confuse the chef syntax to pass an hash to a property. Maybe its with curlys directly?

**Comment by oammis** [comment]
In version 2.0.3, you can use the property `ask_vault_n_days_before_expiry`, to request a new certificate a number of days before  its expiration date.
